### ISSUE TITLE
celeri_report.py default paper

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/celeri#104]
@jploveless I'm looking to figure out the best default behavior for celeri_report and I'd welcome your thoughts.

1. Current state:
- No passed arguments: look in `/runs` directory and report statistics on current run
- `--folder_name_1` only report statistics for specified folder
- `--folder_name_1` and `--folder_name_2` diff statistics for specified folders

2. Proposal:
- No passed arguments: look in `/runs` directory and report diff statistics for two most recent folders
   - This is the thing we want to do most frequently
   - If only one folder exists, report statistics for the only extant folder
- `--folder_name_1` only report statistics for specified folder
- `--folder_name_1` and `--folder_name_2` diff statistics for specified folders

Thoughts?

**Comment by jploveless** [comment]
I think this proposal makes the most sense, as you're right that the most common use case is a comparison. 

Given how similar the timestamp-based run directory names are, I wonder if we could add shortcuts for directory names in reverse chronological order, i.e. 0 is the most recent run, 1 is the previous, 2 is before that. I set up something like this in Blocks, editing your ``newdir.m`` function to take a single optional input argument that would count backwards. Absolute pathnames are always going to least ambiguous, but I wonder if this would help speed up quick comparisons across a sequence of runs.
