### ISSUE TITLE
Did I break the testing workflow? 

### ISSUE THREAD

**Issue by jploveless** [brendanjmeade/celeri#113]
I didn't change any code in 4d0dc3936f4a7057f3438ab4757c97b07c75bfa8 (added some mesh files, added the start of a visualization script) but the testing workflow is failing. I did a fresh pull, but I hadn't updated my local env in while. Could that have caused problems when pushing to remote? Sorry!

**Comment by jploveless** [comment]
Apparently just needed a re-run! All passed now. Sorry for the false alarm!

**Comment by brendanjmeade** [comment]
Whoa.  After reading about this issue (see previous comment) I didn't say that resolving on its own...but I'll take it.

**Comment by jploveless** [comment]
Interesting to read that distutils will go away as of Python 3.12, but it does sound like pinning to an older version of setuptools will keep things functional? 

I know I had encountered some issues with the testing workflow in the past, but now I'll know to try a rerun if I get failed tests upon committing.

**Comment by brendanjmeade** [comment]
I'm not certain.  What do you think about pinging Ben about this since it seems to be related to the building of okada_wrapper?
