### ISSUE TITLE
Global block model characterization test.

### ISSUE THREAD

**Issue by tbenthompson** [brendanjmeade/celeri#16]
Now that we have a seemingly functioning block closure and in polygon test, it would be nice to save to disk the correct polygons and station to block assignments. Then, we can add an automated test to reload those values and check that we can reproduce them. 

This is a kind of test where we are just checking that the outputs aren't changing instead of saying whether those results are correct. The type of test is generally called either a "characterization test" or "golden master test" or "freeze test".

**Comment by brendanjmeade** [comment]
Love the public repo fix.  Done!  Thanks for the suggestion!

**Comment by brendanjmeade** [comment]
As of commit: https://github.com/brendanjmeade/celeri/commit/da58fb1326d2ed7ce67e944eee1154e18984851e there is now a successful global block closure test.  It tests against a concatenated list of all edge_idx indices.

**Comment by tbenthompson** [comment]
Yay!! Exciting.
