### ISSUE TITLE
Fix Windows CI run: okada_wrapper installation is failing

### ISSUE THREAD

**Issue by tbenthompson** [brendanjmeade/celeri#25]
See here: https://github.com/brendanjmeade/celeri/runs/3444895437?check_suite_focus=true

**Comment by brendanjmeade** [comment]
@tbenthompson I removed the Windows test because I don't see supporting Windows as a priority at this time.  I'll close this unless you have any objections.

**Comment by tbenthompson** [comment]
Sounds good to me! I don't think anything here is fundamentally problematic on Windows so it should be easy to add support again later.

**Comment by brendanjmeade** [comment]
Sounds good!
