### ISSUE TITLE
Ben what are the slip components for cutde?

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/celeri#35]
https://github.com/brendanjmeade/celeri/blob/9164da11e1431ed4f8cadf1798eced5748fb7e2d/celeri.py#L1671-L1671

**Comment by brendanjmeade** [comment]
@tbenthompson This is a clarification issue.  What is the default coordinate system that cutde assumes for sense of slip on faults?  Is it Cartesian x, y, z, or strike-, dip-, tensile-slip?  Something else?

**Comment by tbenthompson** [comment]
The `slips` parameter is a numpy array with shape (N, 3) where slips[:,0] is the strike slip component, while component 1 is the dip slip and component 2 is the tensile/opening component.

**Comment by brendanjmeade** [comment]
Thanks!  That's fantastic and makes life really easy because it saves a reference frame conversion!
