### ISSUE TITLE
Locking depth negative sign

### ISSUE THREAD

**Issue by tbenthompson** [brendanjmeade/celeri#45]
I just glanced at the code and saw that you were messing around with locking depth sign. I think part of the confusion if that you have a stray negative sign here where I link below. If you remove the negative sign here, then locking depth in the segment data frame can be positive. 

https://github.com/brendanjmeade/celeri/blob/5a331d35d17fe1f3e10d969af43773957058872e/celeri.py#L1044

**Comment by brendanjmeade** [comment]
Thanks @tbenthompson!  I've fixed this with: https://github.com/brendanjmeade/celeri/commit/2fb96ee02b84e277fa14b8b8f62cee8b1abd21cb and there are examples in a notebook to test this out.
