### ISSUE TITLE
Rename "tde" references to "tri"

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/celeri#59]
Both "tde" and "tri" appear throughout the code and are used pretty interchangeably.  We should be more consistent with this.  Either "tri" throughout or keep "tde" when we are specifically dealing with triangular dislocation elements and not more general mesh issues.

**Comment by brendanjmeade** [comment]
@jploveless I've tried to make this decision more quantitative and found that:

`tde_` occurs 38 times in celeri.py
`tri_` occurs 139 times in celeri.py

Based on the fact that we already have more `tri` references than `tde` I'd suggest changing all `tde` variable names to `tri` in `celeri.py`.  If this sound reasonable to you, I'll go ahead and do that.

**Comment by jploveless** [comment]
Sounds good! `tri` definitely wins that battle!

**Comment by brendanjmeade** [comment]
@jploveless I spent several hours on this today and didn't get things to a stage where I was happy enough to commit it.  The reason is that there are times when `tri` is more sensible and other times when `tde` is more sensible.  I wasn't able to draw a clear line between them, and after working on this, I think I was causing more harm than good.  This is certainly something that we can revisit in the future, but for now I'm going to close this because I don't think it's particularly productive at this time.

**Comment by jploveless** [comment]
I'm sorry that after putting a bunch of time into this there's no straightforward solution. I guess I can see where these terms each have their appropriate places. Yes, let's put it on the list of longer-term issues to revisit.
