### ISSUE TITLE
TDE partials aren't getting properly stored for multiple meshes? 

### ISSUE THREAD

**Issue by jploveless** [brendanjmeade/celeri#77]
I think I’m struggling with some variable assignment things with the TDE partials assigned to the `operators` dict. It seems like `operators.meshes[i].tde_to_velocities` is the same size, regardless of what `i` is equal to, and it always corresponds to the final mesh (Sagami). The `cutde` progress bar indicates that the partials are indeed being calculated for each mesh (the actual number of elements is shown for each of the 3 progress bars) but my interpretation is that they aren’t getting stored correctly and instead the first two are getting overwritten by the final mesh. Is this one of those situations where calling a function doesn’t actually update a variable’s value, or rather it completely replaces the previous values? The `operators` dict is not formally returned from `celeri.get_elastic_operators`.

**Comment by brendanjmeade** [comment]
@jploveless Thanks for this.  I'll work on this tomorrow (Friday) morning!

**Comment by jploveless** [comment]
Seems like it's an issue with the "nesting" of dict entries? Storing as `operators.tde_to_velocities[I]` rather than `operators.meshes[i].tde_to_velocities` returns the correct sizes, both inside and outside of the loop. I wonder if this makes more sense organizationally, too, so that we keep the `operators` dict focused on actual operators rather than with a copy of `meshes`?

**Comment by jploveless** [comment]
https://github.com/brendanjmeade/celeri/commit/f78b89e9970f27eb46240fae1bd87fe75b3e1bae on the `japan_dev` branch now runs, but the solution is terrible, with very fast slip rates on the TDEs and therefore really fast estimated velocities. Changes here (sorry, these should have gone in the commit message) are: 

- Renamed all instances of `operators.meshes[i].variable_name` to just `operators.variable_name[I]` (same with `index.`). I think this is okay, since all `variable_name` items were named to be pretty specific to TDEs, and so hopefully that plus the `[I]` indexing convention is a good reminder that these are variables corresponding to meshes. Many of these changes are in the `celeri_direct_dense_japan.ipynb` notebook, but some are also made in `celeri.py` itself. 
- Edited `celeri.post_process_estimation` to (I think) correctly extract `estimation.tde_rates` and calculate `estimation.vel_tde` for cases of multiple meshes. Previously these seemed set up for just a single mesh. 

I did verify that this new code runs correctly for the Western North America version, so the changes to variable names seem to have not impacted the successful run of a single-mesh model. But, I'm not sure where the issues lie with the Japan model.

**Comment by brendanjmeade** [comment]
@jploveless This is really insightful and a big step in the right direction.  I spent all of last night trying to get the nesting to work, with no luck.  I think your solution is fantastically clean and a wise design decision.

Is there a PR for this commit?  I can't seem to see it on Github.

I'm betting that some of the TDE issues have to do with weighting in the input files.  I had to change this by a factor 1e9 (?) between the blocks files and the celeri files for the Cascadia case.

**Comment by jploveless** [comment]
PR made! That scaling stuff sounds promising, as TDE slip rates were ~1e9. 

I think the GitHub checks are failing because of how the checks are written (referencing now-changed variable names) but not sure…

**Comment by jploveless** [comment]
Oh, another big change is that I added a negative sign in front of the TDE partials when they're placed in the `operator` dict, so that the coseismic contribution is being subtracted from block motions. (Big change in terms of impact on the solution, not in terms of keystrokes)

**Comment by brendanjmeade** [comment]
I'm not sure about why the results seem so off.  I tried increasing the mesh smoothing by 1e9 and it helped a bit but the block solution is still horrible (https://github.com/brendanjmeade/celeri/commit/29aee8c5a1213bf93b9607815a9babbb1b2bcd8a).

@jploveless One thing I'm not sure of is whether the TDE meshes are replacing the correct segments?  I know we usually have a numbering scheme for this that depends on the order of the meshes in mesh_params.json.

Also, for some reason the plotting limits seem to be ignored with the Japan model, so it's really hard to Zoom in and take a look at what's going on (https://github.com/brendanjmeade/celeri/issues/80).

**Comment by brendanjmeade** [comment]
Fixed be @jploveless around February 26th 2022.
